stages:
  - build
  - test
  - dockerize
  - deploy

job_name:
  stage: build
  script:
    - export

cache:
  paths:
    - node_modules/

install_dependencies:
  image: node:latest

  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

build_env_file_ite:
  stage: build
  image: registry.gitlab.com/gitlab-examples/kubernetes-deploy
  script:
    - sed -i "s/FLAG_APP_PORT/$APP_PORT/g" .env.gitlab
    - sed -i "s/FLAG_ENV/development/g" .env.gitlab
    - sed -i "s/FLAG_MONGO/mongodb:\/\/$MONGO_DB_USER_IP:27017\/$MONGO_DB_USER_NAME/g" .env.gitlab
    - sed -i "s/FLAG_USER_ENGINE_URL//g" .env.gitlab
    - sed -i "s/FLAG_USER_ENGINE_PORT//g" .env.gitlab
    - sed -i "s/FLAG_USER_ENGINE_AUTHENTICATION_ROUTE_PATH//g" .env.gitlab
    - mv .env.gitlab .env

# testing_with_yarn:
#   image: node:latest
#   stage: test
#   script: yarn test

build_docker_image:
  stage: dockerize
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg APP_PORT=$APP_PORT -t challenge_image:${CI_COMMIT_SHORT_SHA} .
    - docker push challenge_image:${CI_COMMIT_SHORT_SHA}
    - docker push challenge_image:latest

deploy_to_gke:
  stage: deploy
  image: quay.io/martinhelmich/k8s-deployer:latest
  script:
    - helm upgrade --install --set image.get=${CI_COMMIT_TAG} ${CI_PROJECT_NAME} ./challenge-engine-chart