image: node:latest

stages:
  - build_env_file
  - build_docker_image
  - build_application
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build_application
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

build_env_file_ite:
  stage: build_env_file
  image: registry.gitlab.com/gitlab-examples/kubernetes-deploy
  script:
    - sed -i "s/FLAG_APP_PORT/$APP_PORT/g" .env.gitlab
    - sed -i "s/FLAG_ENV/development/g" .env.gitlab
    - sed -i "s/FLAG_MONGO/mongodb:\/\/$MONGO_DB_USER_IP:27017\/$MONGO_DB_USER_NAME/g" .env.gitlab
    - sed -i "s/FLAG_USER_ENGINE_URL//g" .env.gitlab
    - sed -i "s/FLAG_USER_ENGINE_PORT//g" .env.gitlab
    - sed -i "s/FLAG_USER_ENGINE_AUTHENTICATION_ROUTE_PATH//g" .env.gitlab
    - mv .env.gitlab .env

# testing_testing:
#   stage: test
#   script: yarn test

build_docker_image:
  stage: build_docker_image
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --build-arg APP_PORT=$APP_PORT -t challenge_image .
    - docker push challenge_image